package it.polimi.ingsw.network.message;

public enum MessageType {
    LOGIN_REQUEST, LOGIN_REPLY,
    PLAYERNUMBER_REQUEST, PLAYERNUMBER_REPLY,
    LOBBY,
    GODLIST,
    BOARD,
    INIT_WORKERSPOSITIONS,
    INIT_COLORS,
    PICK_MOVING_WORKER,
    PICK_BUILDING_WORKER,
    MOVE,
    MOVE_FX,
    BUILD,
    BUILD_FX,
    WIN,
    WIN_FX,
    LOSE,

    //utility:
    GAME_LOAD,
    MATCH_INFO,
    DISCONNECTION,
    GENERIC_MESSAGE,
    PING,
    ERROR,
    ENABLE_EFFECT,
    APPLY_EFFECT

}
